# legacy-grid.R  (dev-only)
# Deterministic tree-set grid shared by snapshot-legacy.R (run against the OLD
# capped build) and check-vs-legacy.R (run against the NEW build).  BOTH must see
# byte-identical trees, so every tree is produced from a fixed seed here -- do not
# call any RNG outside legacyTrials(), and do not edit this file between snapshot
# and check.
#
# The grid deliberately spans the MEDIUM-n, many-cluster regime that the
# brute-force strong-cluster oracle (n <= 12) cannot reach -- this is where the
# new fast assembly most needs an exact reference.  R* clade sets are unique
# (Jansson et al. 2016, Lemma 1.1), so new == old is an exact check.

suppressMessages({ library(ape); library(TreeTools) })

.rstarAlign <- function(trees) {
  labs <- trees[[1L]][["tip.label"]]
  lapply(trees, function(tr) TreeTools::RenumberTips(tr, labs))
}

# Named list of tree-sets (each a list of rooted phylo on a shared label set).
legacyTrials <- function() {
  ns      <- c(5L, 8L, 12L, 20L, 35L, 60L, 100L, 150L, 200L)
  ks      <- c(2L, 3L, 5L, 8L)
  regimes <- c("indep", "perturbed", "partly")  # incongruent / congruent / non-binary
  reps    <- 2L
  trials  <- list()
  seedctr <- 7000L
  for (n in ns) for (k in ks) for (regime in regimes) for (rep in seq_len(reps)) {
    seedctr <- seedctr + 1L
    set.seed(seedctr)
    if (regime == "perturbed") {
      base <- ape::rtree(n, rooted = TRUE); base[["edge.length"]] <- NULL
      trees <- lapply(seq_len(k), function(i) {
        tr <- base
        for (s in seq_len(2L)) {            # a couple of tip-label swaps per tree
          ij <- sample.int(n, 2L)
          tr[["tip.label"]][ij] <- tr[["tip.label"]][rev(ij)]
        }
        tr
      })
    } else {
      trees <- lapply(seq_len(k), function(i) {
        tr <- ape::rtree(n, rooted = TRUE)
        if (regime == "partly") tr <- ape::di2multi(tr, tol = 0.25)  # collapse short edges -> fans
        tr[["edge.length"]] <- NULL
        tr
      })
    }
    trials[[sprintf("n%03d_k%d_%s_r%d", n, k, regime, rep)]] <- .rstarAlign(trees)
  }
  trials
}
