// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_quartet_consensus
List cpp_quartet_consensus(const List& splits_list, const int n_tips, const bool init_majority, const bool init_extended, const bool greedy_best_flag, Rcpp::Nullable<Rcpp::IntegerVector> never_drop_r, const double penalty_r);
RcppExport SEXP _Consensus_cpp_quartet_consensus(SEXP splits_listSEXP, SEXP n_tipsSEXP, SEXP init_majoritySEXP, SEXP init_extendedSEXP, SEXP greedy_best_flagSEXP, SEXP never_drop_rSEXP, SEXP penalty_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type splits_list(splits_listSEXP);
    Rcpp::traits::input_parameter< const int >::type n_tips(n_tipsSEXP);
    Rcpp::traits::input_parameter< const bool >::type init_majority(init_majoritySEXP);
    Rcpp::traits::input_parameter< const bool >::type init_extended(init_extendedSEXP);
    Rcpp::traits::input_parameter< const bool >::type greedy_best_flag(greedy_best_flagSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type never_drop_r(never_drop_rSEXP);
    Rcpp::traits::input_parameter< const double >::type penalty_r(penalty_rSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_quartet_consensus(splits_list, n_tips, init_majority, init_extended, greedy_best_flag, never_drop_r, penalty_r));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bhv_distance
double cpp_bhv_distance(IntegerMatrix memA, NumericVector lenA, NumericVector leafA, IntegerMatrix memB, NumericVector lenB, NumericVector leafB);
RcppExport SEXP _Consensus_cpp_bhv_distance(SEXP memASEXP, SEXP lenASEXP, SEXP leafASEXP, SEXP memBSEXP, SEXP lenBSEXP, SEXP leafBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type memA(memASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lenA(lenASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type leafA(leafASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type memB(memBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lenB(lenBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type leafB(leafBSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bhv_distance(memA, lenA, leafA, memB, lenB, leafB));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bhv_tree_at
List cpp_bhv_tree_at(IntegerMatrix memA, NumericVector lenA, NumericVector leafA, IntegerMatrix memB, NumericVector lenB, NumericVector leafB, double lambda);
RcppExport SEXP _Consensus_cpp_bhv_tree_at(SEXP memASEXP, SEXP lenASEXP, SEXP leafASEXP, SEXP memBSEXP, SEXP lenBSEXP, SEXP leafBSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type memA(memASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lenA(lenASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type leafA(leafASEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type memB(memBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lenB(lenBSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type leafB(leafBSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bhv_tree_at(memA, lenA, leafA, memB, lenB, leafB, lambda));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bhv_mean
List cpp_bhv_mean(List mems, List lens, List leaves, int nTip, int maxIter, double tol, int cauchyLength);
RcppExport SEXP _Consensus_cpp_bhv_mean(SEXP memsSEXP, SEXP lensSEXP, SEXP leavesSEXP, SEXP nTipSEXP, SEXP maxIterSEXP, SEXP tolSEXP, SEXP cauchyLengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type mems(memsSEXP);
    Rcpp::traits::input_parameter< List >::type lens(lensSEXP);
    Rcpp::traits::input_parameter< List >::type leaves(leavesSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< int >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type cauchyLength(cauchyLengthSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bhv_mean(mems, lens, leaves, nTip, maxIter, tol, cauchyLength));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Consensus_cpp_quartet_consensus", (DL_FUNC) &_Consensus_cpp_quartet_consensus, 7},
    {"_Consensus_cpp_bhv_distance", (DL_FUNC) &_Consensus_cpp_bhv_distance, 6},
    {"_Consensus_cpp_bhv_tree_at", (DL_FUNC) &_Consensus_cpp_bhv_tree_at, 7},
    {"_Consensus_cpp_bhv_mean", (DL_FUNC) &_Consensus_cpp_bhv_mean, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_Consensus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
