// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// localConsensus
std::string localConsensus(Rcpp::List edgeList, int nTip, bool minrs);
RcppExport SEXP _Consensus_localConsensus(SEXP edgeListSEXP, SEXP nTipSEXP, SEXP minrsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type edgeList(edgeListSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    Rcpp::traits::input_parameter< bool >::type minrs(minrsSEXP);
    rcpp_result_gen = Rcpp::wrap(localConsensus(edgeList, nTip, minrs));
    return rcpp_result_gen;
END_RCPP
}
// consensus_rcpp_selfcheck
int consensus_rcpp_selfcheck();
RcppExport SEXP _Consensus_consensus_rcpp_selfcheck() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(consensus_rcpp_selfcheck());
    return rcpp_result_gen;
END_RCPP
}
// rStarConsensus
std::string rStarConsensus(Rcpp::List edgeList, int nTip);
RcppExport SEXP _Consensus_rStarConsensus(SEXP edgeListSEXP, SEXP nTipSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type edgeList(edgeListSEXP);
    Rcpp::traits::input_parameter< int >::type nTip(nTipSEXP);
    rcpp_result_gen = Rcpp::wrap(rStarConsensus(edgeList, nTip));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Consensus_localConsensus", (DL_FUNC) &_Consensus_localConsensus, 3},
    {"_Consensus_consensus_rcpp_selfcheck", (DL_FUNC) &_Consensus_consensus_rcpp_selfcheck, 0},
    {"_Consensus_rStarConsensus", (DL_FUNC) &_Consensus_rStarConsensus, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_Consensus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
