# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Quartet consensus (C++ implementation)
#'
#' @param splits_list List of raw matrices (one per tree), from as.Splits().
#' @param n_tips Number of tips.
#' @param init_majority Logical: TRUE to start from majority-rule splits.
#' @param init_extended Logical: TRUE to start from extended majority splits.
#' @param greedy_best_flag Logical: TRUE for "best", FALSE for "first".
#'
#' @return A list with `included` (logical), `raw_splits` (raw matrix),
#'   and `light_side` (integer).
#' @keywords internal
cpp_quartet_consensus <- function(splits_list, n_tips, init_majority, init_extended, greedy_best_flag) {
    .Call(`_ConsTree_cpp_quartet_consensus`, splits_list, n_tips, init_majority, init_extended, greedy_best_flag)
}

cpp_bhv_distance <- function(memA, lenA, leafA, memB, lenB, leafB) {
    .Call(`_ConsTree_cpp_bhv_distance`, memA, lenA, leafA, memB, lenB, leafB)
}

cpp_bhv_tree_at <- function(memA, lenA, leafA, memB, lenB, leafB, lambda) {
    .Call(`_ConsTree_cpp_bhv_tree_at`, memA, lenA, leafA, memB, lenB, leafB, lambda)
}

cpp_bhv_mean <- function(mems, lens, leaves, nTip, maxIter, tol, cauchyLength) {
    .Call(`_ConsTree_cpp_bhv_mean`, mems, lens, leaves, nTip, maxIter, tol, cauchyLength)
}

localConsensus <- function(edgeList, nTip, minrs) {
    .Call(`_ConsTree_localConsensus`, edgeList, nTip, minrs)
}

consensus_rcpp_selfcheck <- function() {
    .Call(`_ConsTree_consensus_rcpp_selfcheck`)
}

rStarConsensus <- function(edgeList, nTip) {
    .Call(`_ConsTree_rStarConsensus`, edgeList, nTip)
}

