# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Quartet consensus (C++ implementation)
#'
#' @param splits_list List of raw matrices (one per tree), from as.Splits().
#' @param n_tips Number of tips.
#' @param init_majority Logical: TRUE to start from majority-rule splits.
#' @param init_extended Logical: TRUE to start from extended majority splits.
#' @param greedy_best_flag Logical: TRUE for "best", FALSE for "first".
#'
#' @return A list with `included` (logical), `raw_splits` (raw matrix),
#'   and `light_side` (integer).
#' @keywords internal
cpp_quartet_consensus <- function(splits_list, n_tips, init_majority, init_extended, greedy_best_flag) {
    .Call(`_ConsTree_cpp_quartet_consensus`, splits_list, n_tips, init_majority, init_extended, greedy_best_flag)
}

cpp_bhv_distance <- function(memA, lenA, leafA, memB, lenB, leafB) {
    .Call(`_ConsTree_cpp_bhv_distance`, memA, lenA, leafA, memB, lenB, leafB)
}

cpp_bhv_tree_at <- function(memA, lenA, leafA, memB, lenB, leafB, lambda) {
    .Call(`_ConsTree_cpp_bhv_tree_at`, memA, lenA, leafA, memB, lenB, leafB, lambda)
}

cpp_bhv_mean <- function(mems, lens, leaves, nTip, maxIter, tol, cauchyLength) {
    .Call(`_ConsTree_cpp_bhv_mean`, mems, lens, leaves, nTip, maxIter, tol, cauchyLength)
}

adamsConsensusCpp <- function(edgeList, nTip) {
    .Call(`_ConsTree_adamsConsensusCpp`, edgeList, nTip)
}

frequencyConsensusCpp <- function(edgeList, nTip) {
    .Call(`_ConsTree_frequencyConsensusCpp`, edgeList, nTip)
}

greedyConsensusCpp <- function(edgeList, nTip) {
    .Call(`_ConsTree_greedyConsensusCpp`, edgeList, nTip)
}

looseConsensusCpp <- function(edgeList, nTip) {
    .Call(`_ConsTree_looseConsensusCpp`, edgeList, nTip)
}

majorityPlusConsensusCpp <- function(edgeList, nTip) {
    .Call(`_ConsTree_majorityPlusConsensusCpp`, edgeList, nTip)
}

localConsensus <- function(edgeList, nTip, minrs) {
    .Call(`_ConsTree_localConsensus`, edgeList, nTip, minrs)
}

consensus_rcpp_selfcheck <- function() {
    .Call(`_ConsTree_consensus_rcpp_selfcheck`)
}

rStarConsensus <- function(edgeList, nTip) {
    .Call(`_ConsTree_rStarConsensus`, edgeList, nTip)
}

#' Transfer consensus (C++ implementation)
#'
#' @param splits_list List of raw matrices (one per tree), each from as.Splits().
#' @param n_tip Number of tips.
#' @param scale Logical: use scaled transfer distance?
#' @param greedy_best_flag Logical: TRUE for "best", FALSE for "first".
#' @param init_majority Logical: TRUE to start from majority-rule splits.
#'
#' @return A `LogicalVector` of length n_splits indicating which pooled splits
#'   are included in the consensus, plus attributes "raw_splits" (a raw matrix
#'   of all unique splits) and "light_side" (integer vector).
#' @keywords internal
cpp_transfer_consensus <- function(splits_list, n_tip, scale, greedy_best_flag, init_majority, n_threads = 1L) {
    .Call(`_ConsTree_cpp_transfer_consensus`, splits_list, n_tip, scale, greedy_best_flag, init_majority, n_threads)
}

#' @keywords internal
cpp_tc_profile <- function(splits_list, n_tip, scale, greedy_best_flag, init_majority, n_iter, n_threads = 1L) {
    .Call(`_ConsTree_cpp_tc_profile`, splits_list, n_tip, scale, greedy_best_flag, init_majority, n_iter, n_threads)
}

