# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

localConsensus <- function(edgeList, nTip, minrs) {
    .Call(`_Consensus_localConsensus`, edgeList, nTip, minrs)
}

consensus_rcpp_selfcheck <- function() {
    .Call(`_Consensus_consensus_rcpp_selfcheck`)
}

rStarConsensus <- function(edgeList, nTip) {
    .Call(`_Consensus_rStarConsensus`, edgeList, nTip)
}

cpp_bhv_distance <- function(memA, lenA, leafA, memB, lenB, leafB) {
    .Call(`_Consensus_cpp_bhv_distance`, memA, lenA, leafA, memB, lenB, leafB)
}

cpp_bhv_tree_at <- function(memA, lenA, leafA, memB, lenB, leafB, lambda) {
    .Call(`_Consensus_cpp_bhv_tree_at`, memA, lenA, leafA, memB, lenB, leafB, lambda)
}

cpp_bhv_mean <- function(mems, lens, leaves, nTip, maxIter, tol, cauchyLength) {
    .Call(`_Consensus_cpp_bhv_mean`, mems, lens, leaves, nTip, maxIter, tol, cauchyLength)
}

